### ISSUE TITLE
no mixin named media-breakpoint-up error on "npm run dev"

### ISSUE THREAD

**Issue by samarthdave** [tamu-datathon-org/gigabowser#30]
Error with the following code block. Appears to be a sass include error problem found [here (stackoverflow)](https://stackoverflow.com/a/49447454). We can resolve it eventually when we include bootstrap component by component.

```css
@include media-breakpoint-up(sm) {
  #splash-content {
    justify-content: center;
  }
}
```

![Screenshot from 2020-04-10 21-58-24](https://user-images.githubusercontent.com/4997589/79033769-8111b480-7b76-11ea-9f2e-fc5cfd08fe68.png)
